"""empty message

Revision ID: 992d8a8c05e1
Revises: 
Create Date: 2020-10-30 21:02:29.147938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992d8a8c05e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    # ### end Alembic commands ###
